
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - scipy
  - numpy
  - pycrypto
  - pip
  - matplotlib
  - requests
  - pip:
    - git+https://github.com/AaronWatters/jp_doodle#egg=jp_doodle
  
